### ISSUE TITLE
How to redirect users out from the login page?

### ISSUE THREAD

**Issue by itsdarrylnorris** [piglovesyou/nextjs-passport-oauth-example#3]
### Problem

If the customer already login to the site and for some reason they go back to the login page, I want to take them into a different page to avoid any login confusion. 

In the `login.tsx`, I tried to do something like this but it's not working:

```jsx

export default withIdentity(() => {
  const identity = useIdentity()

  if (!identity) {
    return (
        <main>
        <p>Log in to use</p>
        <p>
           <a href="/api/auth/github">Sign in with github</a>
        </p>
        </main>
     )
  } else {
    useEffect(() => {
      Router.push('/dashboard')
    })

    // TODO: Loading and redirect.
    return <div>redirect</div>
  }
})

```

There seems to be some type of infinite loop.

**Comment by itsdarrylnorris** [comment]
I added some checks in the `identifyUser` and `withIdentity` to make sure we do not get into an infinite loop.


In the `identifyUser` function
```jsx
async function identifyUser(ctx: any): Promise<UserIdentity | undefined | null> {
  const isSSR = Boolean(ctx.req)
  if (isSSR) {
    const composePassport = require('./composePassport')
    const [proxiedReq, proxiedRes] = await composePassport.initializePassport(ctx.req, ctx.res)
    if (!proxiedReq.user) {

      //
      // Checking if the same as the login page
      //
      if (ctx.req.url === loginPage) {
        return null
      }
      return proxiedRes.redirect(loginPage)
    }
    return proxiedReq.user
  } else {
    // @ts-ignore
    let textContent = document.getElementById('__NEXT_DATA__').textContent || ''

     //
     // Checking if the same as the login page
     //
    if (ctx.req.url === loginPage) {
      return null
    }

    // Reuse initial identity result
    const nextData = JSON.parse(textContent)
    return nextData.props.pageProps.user
  }
}
```

And in the `withIdentity` function:
```jsx
    static async getInitialProps(ctx: any): Promise<IdentityProviderProps | undefined> {
     .....

      let user

      // Checking if we have request before checking.
      if (ctx.req) user = await identifyUser(ctx)

      // @ts-ignore
      return { user, ...appProps }
    }
```

This will let me redirect the user into the "/dashboard" if they go back to the login page with a session.

**Comment by piglovesyou** [comment]
Yeah, `/auth/login` is only route you should not wrap with `withIdentity()` since it tries to redirect users to `/auth/login` if users have not authenticated. Your latter one is a good idea though, if you call `identifyUser()` only when `isSSR === true`, we spoil the logic `document.getElementById('__NEXT_DATA__')` in client-side.

I agree that users don't want to see a login screen when they're logged in. Perhaps we should refactor to achieve that, let me try it.

**Comment by piglovesyou** [comment]
@itsdarrylnorris I added the logic redirect `/` to `/auth/login` and `/auth/login` to `/`. I'd like you to take a look an let me know how you see it👍

**Comment by itsdarrylnorris** [comment]
Hey @piglovesyou , 

I kinda like your approach, I port over your changes into my project. I tested out and it looks good.
